name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get install -y g++

    - name: Build and Test All
      run: |
        for dir in "Algoritmos - CORMEN" "BeeCrowd" "HackerRank"; do
          for file in $dir/*.cpp; do
            if [ -f "$file" ]; then
              g++ -o output "${file}" && ./output
            fi
          done
        done
